name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout main
      uses: actions/checkout@v1
      with:
        submodules: true

    - name: Hugo Deploy GitHub Pages
      uses: benmatselby/hugo-deploy-gh-pages@main
      env:
        GITHUB_TOKEN: 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
        HUGO_VERSION: 0.101.0
        HUGO_EXTENDED: true
        TARGET_REPO: bethalageetachandraraju/zanna-research_source.github.io
        TARGET_BRANCH: gh-pages
        TOKEN: ${{ secrets.GH_TOKEN }}
        HUGO_ARGS: --debug
        GO_VERSION: 1.17
